language: ruby
rvm:
  - "2.2.6"
  - "2.3.3"
  - "2.4.0"
  - "2.7.0"
gemfile:
  - "gemfiles/rails4.2.gemfile"
  - "gemfiles/rails5.0.gemfile"
  - "gemfiles/rails5.1.gemfile"
  - "gemfiles/rails6.0.gemfile"
